NUMPY BASIC

In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [5]:
for i in list_ :
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [7]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [11]:
arra_list = np.array(object = list_, dtype = int)

In [15]:
for i in list_ :
    print(type(i))
    
for i in arra_list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [16]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [18]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.shape(num_array)

(2, 3)

In [20]:
np.size(num_array)

6

In [26]:
np.array([
    [0,0,0],
    [0,0,0],
    [0,0,0]
])

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [27]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
arra_list

array([1, 2, 3, 4, 5])

In [13]:
type(arra_list)

numpy.ndarray

In [14]:
type(list_)

list

In [2]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [3]:
type(array_list)

numpy.ndarray

In [4]:
type(list_)

list

In [ ]:
QUESTION 1 :
    
YES, there is a difference between the data type of variables list_ and array_list .
type(list_)   # this will give a list data type
type(array_list) #this will give ndarray data type

In [ ]:
QUESTION 2 :
    
for i in list_ :
    print(type(i))
    
for i in array_list:
    print(type(i))

In [ ]:
QUESTION 3 :

arra_list = np.array(object = list_, dtype = int)
YES, there is a difference between the data type of variables list_ and arra_list .
for i in list_ :
    print(type(i))
    
for i in arra_list:
    print(type(i))

In [ ]:
QUESTION 4 :
    
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

(i) np.shape(num_array)
(ii) np.size(num_array)

In [ ]:
QUESTION 5 :
    
import numpy as np
null_matrix = np.array([
    [0,0,0],
    [0,0,0],
    [0,0,0]
])
null_matrix

In [ ]:
QUESTION 6 :
    
import numpy as np
identity_matrix = np.identity(5)
identity_matrix